### ISSUE TITLE
Unable to resolve module `./react-native-web.css`

### ISSUE THREAD

**Issue by ponleukea** [gusgard/react-native-swiper-flatlist#103]
error: Error: Unable to resolve module `./react-native-web.css` from `node_modules/react-native-swiper-flatlist/src/components/SwiperFlatList/SwiperFlatList.tsx` at Version 3.x

**Comment by LuffyAnshul** [comment]
I have faced the same Issue please can someone help

**Comment by gusgard** [comment]
Are you using react native web ?

**Comment by LuffyAnshul** [comment]
>I am working with `react-native-cli` and I am not using `react native web`
> Are you using `react native web` ? Version 3.0.8 doesn’t have the support so it should work well until we have a better idea. 
> Are you using `expo` or just `react native` with `react native web`? which versions ?

I am working with `react-native-cli` and I am not using `react native web`

**Comment by gusgard** [comment]
Thanks, I have an idea of how to fix it. For now I recommend you to use version 3.0.8

**Comment by gusgard** [comment]
Fixed with 3.0.13
