### ISSUE TITLE
Can't auto play when index = 0

### ISSUE THREAD

**Issue by QuyetAQ** [gusgard/react-native-swiper-flatlist#109]
Here's my code. Autoplay just running after first swipe. 
Please check this issue. 
Thank you.
`<SwiperFlatList
      autoplay
      autoplayDelay={3}
      autoplayLoop={false}
      index={0}
      showPagination={false}
      renderAll
      autoplayLoopKeepAnimation
      onChangeIndex={handleExtendData}
      data={listPhotos}
      renderItem={({ item }) => (
          <Image
            style={{
              width: width,
              height: height,
            }}
            source={{
              uri: item.urls.small,
            }}
          />
      )}
    >
    </SwiperFlatList>`

**Comment by EshaghiEhsan** [comment]
I have the same issue and I don't know what to do!!!!

**Comment by sofiaringstrom** [comment]
Having this issue as well. @gusgard Tracked it down to the SwiperFlatList component. In the useEffect (row 140) that sets the timer for the autoplay the hook is not listening for changes in the data. Adding _data to the hook it works as expected.

![Screenshot 2021-08-23 at 22 19 18](https://user-images.githubusercontent.com/11421213/130513778-076d3dbb-a48a-4bce-966b-0e0f84566fcb.png)

**Comment by sofiaringstrom** [comment]
@Bharatji If you don't wanna wait for this package to be updated you can use my fork https://github.com/sofiaringstrom/react-native-swiper-flatlist

**Comment by Bharatji** [comment]
Thank you @sofiaringstrom . Let me try this. Appreciate your prompt reply/help.

**Comment by Bharatji** [comment]
Thankyou @sofiaringstrom . Works like a charm

**Comment by gusgard** [comment]
Thanks @sofiaringstrom for your fix, I will release it this week

**Comment by gusgard** [comment]
Fixed in version 3.0.15 by @sofiaringstrom
