### ISSUE TITLE
App crashed in Release mode(Android)

### ISSUE THREAD

**Issue by reactProjects7** [gusgard/react-native-swiper-flatlist#111]
App is working fine in android debug mode, but when i run my app in release mode app is crashed . I have attached below release mode error. 

![1619861129661](https://user-images.githubusercontent.com/80164724/116778123-be9cf480-aa8d-11eb-83bc-05dfe01bb969.jpg)

**Comment by allindeveloper** [comment]
I am also experiencing this issue

**Comment by allindeveloper** [comment]
i was using react-native-svg to render svgs on each `<View/>` insider `<Swiper/>`
this solved my issue
https://github.com/react-native-svg/react-native-svg#problems-with-proguard
