### ISSUE TITLE
error: bundling failed: SyntaxError

### ISSUE THREAD

**Issue by studiozocaro** [gusgard/react-native-swiper-flatlist#121]
error: bundling failed: SyntaxError: /node_modules/react-native-swiper-flatlist/index.ts: Unexpected token (4:12)
   1 |  import { SwiperFlatList, Pagination, PaginationProps, SwiperFlatListProps } from './src/components';
  2 | export default SwiperFlatList;
  3 | export { SwiperFlatList, Pagination };
> 4 | export type { PaginationProps,SwiperFlatListProps};

React Native version:

"react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-native": "0.61.5",

**Comment by gusgard** [comment]
Could you upgrade your babel version to `7.9.0` or above? It seems the error is because your current version doesn't support `export type` https://github.com/babel/babel/pull/11171

https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611419607
