### ISSUE TITLE
E/unknown:FabricViewStateManager: setState called without a StateWrapper

### ISSUE THREAD

**Issue by GianlucaP99** [gusgard/react-native-swiper-flatlist#122]
When using the SwiperFlatList component I get the error: "E/unknown:FabricViewStateManager: setState called without a StateWrapper". The error is not blocking and I notice it from the android studio console.

--------------------------------------------------------------------------------------------------------------
react-native-cli: 2.0.1
React Native version: 0.64.2

System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 17.44 GB / 31.72 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
      Versions: 10.0.16299.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: 16.9.31205.134 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.11
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

--------------------------------------------------------------------------------------------

## Steps To Reproduce

1. clone from my [repo](https://github.com/GianlucaP99/testSwiperFlatList)
2. cd repo; npm install;
3. npx react-native start
4. run from android studio

Describe what you expected to happen:
everything will seem to work but in android studio console the error will appear.

Snack, code example, screenshot, or link to a repository:
[link repo](https://github.com/GianlucaP99/testSwiperFlatList)

**Comment by kishanbarmawala** [comment]
Did anyone get solution, I am also facing this issue

**Comment by Gerlison** [comment]
I'm facing the same error and it's caused by ScrollView, on scroll action. Every time I scroll, this warning is thrown on logcat

**Comment by gusgard** [comment]
I think the error you are describing is the same as this one from the RN repository https://github.com/facebook/react-native/issues/32070. I think there isn't much I can do
