### ISSUE TITLE
Exception: scrollToIndex out of range: requested index 3 but maximum is 1.

### ISSUE THREAD

**Issue by GuoYongming** [gusgard/react-native-swiper-flatlist#123]
React Native version:
"react-native": "0.63.3"

react-native-swiper-flatlist version:
"react-native-swiper-flatlist": "3.0.14"

## Steps To Reproduce

1. I just use this module as a slider with 5 items in my Browse Page, click one item and then go to a detail page.
2. In detail page, i clicked a favorite button and sent a message to refresh Browse Page.
3. The Browse page server data returned with 2 slider items, then i got this exception.

Expected : render again and scroll to first one, then auto animation.

There's my code:
``` 
            <SwiperFlatList
                autoplay
                autoplayDelay={2}
                autoplayLoop
                showPagination
                data={this.heroesPayload}
                paginationStyle={styles.slideIndicatorContainer}
                paginationStyleItem={styles.slideIndicator}
                paginationStyleItemActive={styles.slideIndicatorActive}
                paginationStyleItemInactive={styles.slideIndicatorInActive}
                index={0}
                renderItem={({ item }) => (
                  <Hero
                    adConfig={adConfig}
                    componentId={componentId}
                    data={item}
                    imageHeight={this.imageHeight}
                    key={item.heroId}
                    withInlineText={this.withInlineText}
                  />
                )}
              />
```

![Simulator Screen Shot - iPhone 11 - 2021-06-24 at 17 57 43](https://user-images.githubusercontent.com/8219653/123244047-2152bf80-d516-11eb-8801-a4b01dcaa448.png)

**Comment by dytra** [comment]
should've call like this
```
ref.scrollToIndex({index:2});
```
