### ISSUE TITLE
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.

### ISSUE THREAD

**Issue by Bharatji** [gusgard/react-native-swiper-flatlist#127]
I get the following error when I pass regular Json Response (passing only the text row out of 5 other rows with text lengths more than around 200 chars. I This case I need to kick start (like a scooter) swipe for the first time after which Swipe works. 

error - VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. Object {
  "contentLength": 2986.9091796875,
  "dt": 2098,
  "prevDt": 1706,
}

**Comment by gusgard** [comment]
Could you add an example in expo.io so I can reproduce it? We which version are you using of the library ? Because we aren't using classes and that message seems old. Thanks.

**Comment by aoulaa** [comment]
have the same problem 

here is my code:

            <SwiperFlatList
                nestedScrollEnabled={true}
                renderAll={true}
                autoplay
                autoplayLoop
                data={perks}
                renderItem={useMemo(() => ({ item }) => <Any item={item} />, [perks])}
            />
