### ISSUE TITLE
Varying height on different children

### ISSUE THREAD

**Issue by Rodrigo77777** [gusgard/react-native-swiper-flatlist#13]
It seems when you have children with differing heights the Swiper takes the height of the largest child, regardless of which index you are currently on. Any chance this can be changed so it takes the height of the current index instead?

**Comment by gusgard** [comment]
Hi, could you give me an example and I will take a look this week? Is using the prop `vertical`?

**Comment by h406621397** [comment]
Unsupported top level event type "topScroll" dispatched
extractEvents
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3519:22
extractEvents
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3298:71
handleTopLevel
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3539:64
<unknown>
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3560:55
batchedUpdates
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2754:26
batchedUpdates
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:202:35
batchedUpdatesWithControlledComponents
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:209:34
_receiveRootNodeIDEvent
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3559:50
receiveEvent
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3564:60
__callFunction
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:302:47
<unknown>
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:116:26
__guard
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:265:6
callFunctionReturnFlushedQueue
    E:\RN\OpenSource\react-native-swiper-flatlist\example\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115:17

**Comment by gusgard** [comment]
@h406621397 That errors seem related to the version of RN in the example folder, I updated to the latest, it should work. https://github.com/gusgard/react-native-swiper-flatlist/tree/master/example

**Comment by pgpankajbigstep** [comment]
> Hi, could you give me an example and I will take a look this week? Is using the prop `vertical`?

Hey @gusgard : Did you get any solution for this ?

**Comment by keshk26** [comment]
Is there any solution for this? I am running into the same issue where the swiper takes the height of the largest child and is not dynamic.

**Comment by vaccarov** [comment]
I also face the same problem.
Unfortunately this is a deal breaker for using this library
