### ISSUE TITLE
Block swipe direction

### ISSUE THREAD

**Issue by ithustle** [gusgard/react-native-swiper-flatlist#130]
Hello,

First of all, thank you for this great lib. Its very helpful.

I'd like to know if is it possible block swipe direction to left or right?

**Comment by gusgard** [comment]
@ithustle i think you are looking for the property `disableGesture=true`

**Comment by ithustle** [comment]
@gusgard  hum... Thanks to reply. This property will allow me to block all directions or just one of them?

**Comment by gusgard** [comment]
It will block all the directions
