### ISSUE TITLE
SwiperFlatlist renders another invisible component that streches outside the screen

### ISSUE THREAD

**Issue by reuvensnappy** [gusgard/react-native-swiper-flatlist#131]
Sometimes i am able to swipe more than expected outside of the boundaries of my rendered components.
When inspecting the elements i can see that an additional element is being rendered with a large width ( this element does not come from the data provided to the swiper).
I was not able to found its origin.

Thank you for the support.

React Native version: 0.66.3
Swiper version: 3.0.16

Screenshot: 
![Screen Shot 2022-01-09 at 10 39 08](https://user-images.githubusercontent.com/97031951/149347122-b3930c7b-5192-46b8-a6ca-c66ca93d9ecc.png)

**Comment by Benj846** [comment]
same here

**Comment by gusgard** [comment]
Hey, could you add an example in expo ? Eg https://snack.expo.dev/@gusgard/react-native-swiper-flatlist

**Comment by pgpankajbigstep** [comment]
> same here

Hey @Benj846 Did you get any solution for the same?
