### ISSUE TITLE
Manual swipe issue

### ISSUE THREAD

**Issue by Priyadharshini-max** [gusgard/react-native-swiper-flatlist#138]
I'm facing this issue , only when I swipe manually. It display only half image, like this
![Screenshot_2022-06-03-12-43-05-61_4007cdf3d38763fe5bc19f163cbad3b9__01](https://user-images.githubusercontent.com/59358875/171807576-966b268f-f3ea-486b-a03c-0f4d32044ae4.jpg)
![Screenshot_2022-06-03-12-43-02-16_4007cdf3d38763fe5bc19f163cbad3b9__01](https://user-images.githubusercontent.com/59358875/171807607-e04bcba7-6389-4a45-90cb-108c7b889673.jpg)

I want to display like this,

![Screenshot_2022-06-03-12-46-57-04_4007cdf3d38763fe5bc19f163cbad3b9__01](https://user-images.githubusercontent.com/59358875/171807702-39da4080-a6e8-4995-9e7b-77d0b1424928.jpg)

**Comment by gusgard** [comment]
Hey @Priyadharshini-max , could you create an example in snack.expo.dev ? (https://snack.expo.dev/@gusgard/react-native-swiper-flatlist)
