### ISSUE TITLE
Listen to autoplay changes

### ISSUE THREAD

**Issue by Slyther** [gusgard/react-native-swiper-flatlist#143]
Similar to what was mentioned in #135 , I'm finding that I'm having to conditionally add or remove the autoplay props for play/pause functionality rather than just update the autoplay prop with a variable.

![image](https://user-images.githubusercontent.com/4093602/176585423-35e828ae-9451-4023-91f0-f81ce726847f.png)

Not completely module breaking as the functionality works as intended when doing this, but ideally there shouldn't have to be a workaround.

I'm using react-native-windows 0.66.5 and react-native 0.66, as well as react-native-swiper-flatlist 3.0.17.

**Comment by gusgard** [comment]
Fixed in [3.0.18](https://www.npmjs.com/package/react-native-swiper-flatlist/v/3.0.18)
