### ISSUE TITLE
RTL Suppor is missing. 

### ISSUE THREAD

**Issue by saadi-ninjasCode** [gusgard/react-native-swiper-flatlist#149]
In RTL  mode, **Flatlist** `renderItem` is called continuously 

I debug the issue and I found that  in **SwiperFlatList.tsx**
 `_onViewableItemsChanged` method is called continuously with incorrect indexing.
 
 If anyone found a solution. Please let me know.

**Comment by gusgard** [comment]
Added support for RTL in `3.2.2`
