### ISSUE TITLE
SwiperFlatList not swipeable in gorhom/bottom-sheet on Android 

### ISSUE THREAD

**Issue by chloezxyy** [gusgard/react-native-swiper-flatlist#150]
To import { FlatList } from 'react-native-gesture-handler' instead of from 'react-native' library as the SwiperFlatList component will not be swipeable on android devices when using within the @gorhom/bottom-sheet library. It works fine on ios devices

React Native version: "react-native": "0.69.5"

## Steps To Reproduce

1.
2.

Describe what you expected to happen:
- SwiperFlatList component will be horizontally scrollable/swipeable when used on BottomSheet

Snack, code example, screenshot, or link to a repository:

**Comment by gusgard** [comment]
@chloezxyy could you create an example with @gorhom/bottom-sheet or share the code you were trying ?

**Comment by jaakola-aleksanteri** [comment]
@gusgard I have the same problem. Issue is only regarding to Android, iOS works as expected. Is this resolved or? i can create a new issue with a snack.
