### ISSUE TITLE
disableGesture cannot be updated on the fly

### ISSUE THREAD

**Issue by lsps9150414** [gusgard/react-native-swiper-flatlist#151]
From the source code, it seems that `disableGesture` only accepts the initial value but cannot be updated after initialization.
(source code: https://github.com/gusgard/react-native-swiper-flatlist/blob/master/src/components/SwiperFlatList/SwiperFlatList.tsx#L76)

It would be nice if it accepts changes, otherwise, it would be better to name the prop something like `initDisableGesture`, similarly to how the `initValue` prop may exist for an input component along side a `value` prop.

**Comment by gusgard** [comment]
Fixed in [3.0.18](https://www.npmjs.com/package/react-native-swiper-flatlist/v/3.0.18)
