### ISSUE TITLE
SwiperFlatList not swipeable in gorhom/bottom-sheet on Android

### ISSUE THREAD

**Issue by jaakola-aleksanteri** [gusgard/react-native-swiper-flatlist#153]
React Native version: 0.70.6

## Steps To Reproduce

1. Check my linked repository and try press `"PRESENT MODAL" `
2. Try to swipe 

Describe what you expected to happen:

Swiping on Android would work as it works on iOS

Snack, code example, screenshot, or link to a repository:

https://github.com/jaakola-aleksanteri/react-native-swiper-gorhom-modal-bug

**Comment by jaakola-aleksanteri** [comment]
I have traced the bug to the `RestureHandlerRootView` from react-native-gesture-handler. I think one possible fix could be using `FlatList` from react-native-gesture-handler. https://gorhom.github.io/react-native-bottom-sheet/troubleshooting

**Comment by gusgard** [comment]
@jaakola-aleksanteri thanks for the example, I will add support for `react-native-gesture-handler` in the next release ( probably next week )

**Comment by gusgard** [comment]
@jaakola-aleksanteri Added `useReactNativeGestureHandler`
