### ISSUE TITLE
RenderItem is returning index always equal to 0

### ISSUE THREAD

**Issue by jeffsmonteiro** [gusgard/react-native-swiper-flatlist#160]
React Native version:
0.67

## Steps To Reproduce
`
// Render function
const _renderItem = (item, index) => {
    console.log('item', item);
    console.log('index', index);
}

// Render Return
<SwiperFlatList
  data={mydata}
  renderItem={({ item, index }) => _renderItem(item, index)}
/>
`
## Expected
The render function should receive the correct index value

**Comment by gusgard** [comment]
Thanks for reporting this issue. I will take in a few days.

**Comment by gusgard** [comment]
@jeffsmonteiro I created this example, and it seems to work fine. https://snack.expo.dev/@gusgard/react-native-swiper-flatlist-v2

Could you create and example in which I can reproduce it? Also, let me know which version were you using of the library. Thanks
