### ISSUE TITLE
How can i get current Item Value & for the first time load all the component simultaneously

### ISSUE THREAD

**Issue by iasreact1** [gusgard/react-native-swiper-flatlist#162]
@gusgard  Is there any way to get current item details from here and when the list first time render it render all the items simultaneously though in view port there is the only first item. I want one by one item render which is in view port and get all the item details like for my case i use video view and onLoad called for all the item simultaneously here

**Comment by gusgard** [comment]
hey @iasreact1 , I'm not really following what you mean, did you try the prop `renderAll`? Or elaborate a bit more your issue ? Thanks
