### ISSUE TITLE
On scroll to index image is shown with part of next image (Only when data length is bigger than 2)

### ISSUE THREAD

**Issue by ShmuelPick** [gusgard/react-native-swiper-flatlist#168]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by gusgard** [comment]
Can you reproduce this on Snack Expo or create a running example?
https://snack.expo.dev/@gusgard/react-native-swiper-flatlist-simple-with-renderitems-and-data @ShmuelPick
