### ISSUE TITLE
While given scroll to index it is not scroll to 11 it only scroll to 10 when there is 15 data or more

### ISSUE THREAD

**Issue by Ram200231** [gusgard/react-native-swiper-flatlist#170]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by TimHero** [comment]
the scroll is 0 indexed. Meaning your first item is item 0, your second is item 1 etc. Like with arrays in javascript.

**Comment by gusgard** [comment]
Should be fixed in `3.2.4`
