### ISSUE TITLE
Can't make spacing between 2 sliders

### ISSUE THREAD

**Issue by CMDezz** [gusgard/react-native-swiper-flatlist#171]
How can we set spacing between 2 sliders guys ? 
![image](https://github.com/gusgard/react-native-swiper-flatlist/assets/53512796/7d4179fb-63f5-41f0-8ea6-5c44ad830fea)

**Comment by gusgard** [comment]
This is a wrapper around FlatList, using `ItemSeparatorComponent={() => <View style={{height: 20}} />}` should help you.
