### ISSUE TITLE
Nested Swiper Flatlists layout bug

### ISSUE THREAD

**Issue by AhmadNaeemK** [gusgard/react-native-swiper-flatlist#173]
Thanks for the awesome library. ❤️ 
I have to nest one `SwiperFlatList` for images to another `SwiperFlatList` for a card. And after nesting the internal `SwiperFlatList` expands vertically and becomes not scrollable.

<img width="378" alt="Screenshot 2023-06-23 at 4 13 34 AM" src="https://github.com/gusgard/react-native-swiper-flatlist/assets/46021475/67dc7791-df81-46b1-ba03-3da5b4a74165">

React Native version:
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 580.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.08.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found

## Steps To Reproduce

1. Create a swiperFlatList (List A)
2. Create another SwiperFlatList that renders the previous SwiperFlatlist (List A) in its items.

Describe what you expected to happen:

<img width="385" alt="Screenshot 2023-06-23 at 4 12 30 AM" src="https://github.com/gusgard/react-native-swiper-flatlist/assets/46021475/e7b0fed1-5ca3-40f5-9dfc-a1f1233d17a7">

Snack, code example, screenshot, or link to a repository:
```
export const Test = ({testProfiles}) => {
    const renderProfilePhoto = ({ item }) => <ProfilePhoto photoUrl={item.url} />;

    const renderItem = ({ item }) => (
        <View
            style={{
                width: SCREEN_WIDTH,
                height: 200,
            }}
        >
            <Text>{item.firstName}</Text>
            <SwiperFlatList
                data={item.profile?.mediaList}
                renderItem={renderProfilePhoto}
                showPagination
            />
        </View>
    );

    return (
        <PeopleScreenContainer>
            <SwiperFlatList
                data={testProfiles}
                renderItem={renderItem}
                ref={scrollRef}
            />
     );
 };
```

**Comment by gusgard** [comment]
You can find an example in the issue https://github.com/gusgard/react-native-swiper-flatlist/issues/99#issuecomment-756995735

you can scroll in the 5.1 item
https://snack.expo.dev/@gusgard/react-native-swiper-flatlist-using-scrollview

**Comment by AhmadNaeemK** [comment]
Thanks that helped a lot. I tried it but could not achieve what I wanted to do and took your advice of not having a horizontal list inside another.
