### ISSUE TITLE
Changing the distance between the dots on Pagination

### ISSUE THREAD

**Issue by angielt** [gusgard/react-native-swiper-flatlist#174]
Can't seem to figure out how to change the distance between the dots in pagination through the styling. Any other ways?

**Comment by gusgard** [comment]
You need to define your one custom pagination. eg:

https://github.com/gusgard/react-native-swiper-flatlist/blob/03399750cfde3698135d6bbbed4c0f4829fc9739/example/src/SwiperWithRenderItems.tsx#L39

https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/CustomPagination.tsx#L14
