### ISSUE TITLE
Setting children width causes glitchy behavior

### ISSUE THREAD

**Issue by Nonononoki** [gusgard/react-native-swiper-flatlist#178]
I want to create a simple responsive carousel for images in react native.

React Native version: 0.72.0

## Steps To Reproduce
Simply set the width of the children to a fixed value instead of full width

Describe what you expected to happen:
When switching to next child the next child should be displayed.

What happens:
Some images are skipped, sometimes depending of the width of the browser window.

Snack, code example, screenshot, or link to a repository:
https://snack.expo.dev/Gjz-RIIn_

**Comment by Nonononoki** [comment]
Solved it by overriding `getItemLayout`
```
            getItemLayout={(data, index) => (
              {length: maxWidth, offset: maxWidth * index, index: index}
            )}
```

**Comment by Rose-wu** [comment]
Thank you very much
