### ISSUE TITLE
Scrolling disrupted after the 12th item in vertical SwiperFlatList

### ISSUE THREAD

**Issue by MiteshKalal7** [gusgard/react-native-swiper-flatlist#180]
I am encountering an issue with a vertical FlatList, specifically in the SwiperFlatList component. The FlatList functions properly until index 12, after which its behavior becomes erratic.

On the screen containing the FlatList, there is a BOTTOM_TAB_HEIGHT with a height of 50. The renderItem component's height is set to (deviceHeight - BOTTOM_TAB_HEIGHT).

Here is the code for the SwiperFlatList:
`<View
  style={{
    backgroundColor: "black",
    flex: 1,
  }}
>
  <SwiperFlatList
    ref={scrollViewRef}
    vertical={true}
    onChangeIndex={handleChangeIndexValue}
    contentContainerStyle={{ backgroundColor: "black" }}
    data={data}
    renderItem={({ item, index }) => {
      return <Item item={item} index={index} currentIndex={currentIndex} />;
    }}
    getItemLayout={(_d, i) => ({
      length: deviceHeight,
      index: i,
      offset: (deviceHeight - BOTTOM_TAB_HEIGHT) * i,
    })}
    keyExtractor={(_, index) => index}
  />
</View>
`

![Simulator Screenshot - iPhone 15 - 2023-11-04 at 18 29 44](https://github.com/gusgard/react-native-swiper-flatlist/assets/52530388/3583e555-1ad2-4166-a187-98d9bf96a072)
![Simulator Screenshot - iPhone 15 - 2023-11-04 at 18 29 54](https://github.com/gusgard/react-native-swiper-flatlist/assets/52530388/c27260a4-dc16-4c72-a57c-5db53d1b574e)

**Comment by ArtyomHovhannisyann** [comment]
Have you found the solution?

**Comment by MiteshKalal7** [comment]
> Have you found the solution?

Nope, I ended up with full screen height to video.

**Comment by ArtyomHovhannisyann** [comment]
You hide your bottom tab?

**Comment by ArtyomHovhannisyann** [comment]
@gusgard Do you have any solution?

**Comment by MiteshKalal7** [comment]
> Do you hide your bottom tab?

Nope, it’s still there, video is being cut from that part.

**Comment by gusgard** [comment]
Should be fixed in `3.2.4`
