### ISSUE TITLE
How to add scroll in pagination

### ISSUE THREAD

**Issue by ahsan-storm** [gusgard/react-native-swiper-flatlist#19]
Let's say I have 20+ children for the swiper flatlist. How should I achieve scroll in pagination?

**Comment by gusgard** [comment]
Did you try adding `showsHorizontalScrollIndicator`? eg: `<SwiperFlatList showsHorizontalScrollIndicator>`

More: https://facebook.github.io/react-native/docs/scrollview#showshorizontalscrollindicator
