### ISSUE TITLE
feature discussion: FlatListComponent as prop, so we can use "react-native-gesture-handler" FlatList

### ISSUE THREAD

**Issue by younes0** [gusgard/react-native-swiper-flatlist#190]
Problem: with the default FlatList, if you scroll a horizontal ScrollView, the parent element will be scrolled too (eg: React Navigation Tabs)
This doesn't happen with the more enhanced "react-native-gesture-handler" FlatList.

Solutions:
- Use "react-native-gesture-handler" FlatList and add dependency 
- Add a prop `FlatListComponent `, so we can pass "react-native-gesture-handler"'s FlatList  without adding `rngh `as dependency.

**Comment by gusgard** [comment]
@younes0 this is already implemented check https://github.com/gusgard/react-native-swiper-flatlist?tab=readme-ov-file#react-native-gesture-handler
