### ISSUE TITLE
Broken on Android with React Native 0.57

### ISSUE THREAD

**Issue by raynor85** [gusgard/react-native-swiper-flatlist#21]
Snap stopped working on RN 0.57 on Android devices
![bug-android](https://user-images.githubusercontent.com/5817333/46052251-62370300-c135-11e8-81d3-457a842e5bf0.gif)

**Comment by gusgard** [comment]
Thanks for reporting this bug. I will take a look in the weekend

**Comment by gusgard** [comment]
Is a bug in the react-native library, it should be fixed in `0.57.2`

https://github.com/facebook/react-native/issues/21302

**Comment by gusgard** [comment]
Fixed in version `0.57.2`
