### ISSUE TITLE
How to get previous and next index on scroll

### ISSUE THREAD

**Issue by Rinkuk1993** [gusgard/react-native-swiper-flatlist#22]
onMomentumScrollEnd() provides only current index.

How to get previous and next index. It helps to complete some actions to previous index once swipe is initiated.

I have tried onMomentumScrollBegin(). The problem I face here is it gives the previous index wrongly if I scroll backward. 
Example - ( Screen0 > Screen 1 > Screen 2)
If I scroll from Screen 0 -> 1 (I get index =0 )
If I scroll from Screen 1 -> 0 (I get index =0 )

Please let me know if it work

**Comment by gusgard** [comment]
Did you try using `ref`? https://github.com/gusgard/react-native-swiper-flatlist/blob/master/src/components/SwiperFlatList/index.js#L171
Maybe something like `yourComponent.flatListRef.paginationIndex` is what you wants.

**Comment by Rinkuk1993** [comment]
This will give me again current Index if I am not wrong. 
I have used component variable oldIndex to use and compare to get Last slide, the first slide and complete action on oldIndex on each swipe or slide jump.

**Comment by jackyleehong** [comment]
any update on this? how to get the index on swipe?

**Comment by gusgard** [comment]
Yes, you can use `onChangeIndex` in version 2, check the readme https://github.com/gusgard/react-native-swiper-flatlist#functions and a working example in https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/SwiperWithChildren.js#L28
