### ISSUE TITLE
SwiperFlatList with RefreshControl

### ISSUE THREAD

**Issue by ramonitor** [gusgard/react-native-swiper-flatlist#24]
Hi, can you confirm SwiperFlatList control not (yet) supports the refreshControl prop? Adding the following code does not give the ability to pull to refresh. 

```
refreshControl={
    <RefreshControl
        colors={['#9Bd35A', '#689F38']}
        refreshing={fetching}
        onRefresh={this.refreshData}
        title="Pull to refresh"
        tintColor="#fff"
        titleColor="#fff"
    />
}
```

**Comment by gusgard** [comment]
It should work, I will take a look this weekend

**Comment by gusgard** [comment]
You can add the ability to pull to refresh if you wrap each component of the children/renderItem into a ScrollView
