### ISSUE TITLE
The scroll speed on Android is too slow

### ISSUE THREAD

**Issue by Bvnkame** [gusgard/react-native-swiper-flatlist#28]
Thanks for this awesome swiper flatlist,
I have tried the scroll of this plugin on both iOs and Android,
but I got a issue with scroll on Android, it is scroll slowly and also scroll to other items
Ex: we have 4 slides, we are in slide 1, tap the screen then swipe left, it's scroll slowly and take us to slide 4
Im using Android 8.1
Device: Xiaomi redmi 5 plus

**Comment by ttibau** [comment]
+1

**Comment by EzenwakaKaycee** [comment]
please, how can I control the auto scroll speed?
