### ISSUE TITLE
Feature request: insert previous and next arrows

### ISSUE THREAD

**Issue by HighSoftWare96** [gusgard/react-native-swiper-flatlist#31]
A good feature to add is the previous and next arrows like this:

![image](https://user-images.githubusercontent.com/22793967/51107462-295b9080-17ef-11e9-8be7-815f89cdc007.png)

**Comment by borgogelli** [comment]
+1

**Comment by gusgard** [comment]
You can re-define `PaginationComponent` to add the arrows there.
Check https://github.com/gusgard/react-native-swiper-flatlist#props and https://github.com/gusgard/react-native-swiper-flatlist/blob/master/src/components/Pagination/index.js

**Comment by pl709** [comment]
To enable a "go previous slide" function you could use this:
const goToPreviousIndex = () => {
  const currIndex = scrollRef.current.getCurrentIndex();
  if(currIndex-1>0){
    scrollRef.current.scrollToIndex({ index: currIndex-1 });
  }
};

after attaching a ref scrollRef to the SwiperFlatList : ref={scrollRef} using the useRef hook

Then you could attach the function to an absolutely positionned arrow beside the swiper using a TouchableOpacity with an onPress property : onPress={goToPreviousIndex} 

It works for me. Hope it helps!

NB: great package !
