### ISSUE TITLE
renderItem is rendering many times and bumping up

### ISSUE THREAD

**Issue by nateblog** [gusgard/react-native-swiper-flatlist#32]
The renderItem function is rendering many times if you add SwiperFlatList inside a modal.

Replicate:

1. Create a modal
2. Add SwiperFlatList that uses renderItem function inside modal
3. Close and open the modal many times
4. Log the data being returned inside renderItem function

This will show you the issue, something is bumping up. When you open and close the modal 10 times, the renderItem function also returns 10 times.

**Comment by gusgard** [comment]
Could you try it again with version 2? And add a working example?
