### ISSUE TITLE
Doc question: how to use getCurrentIndex?

### ISSUE THREAD

**Issue by greenais** [gusgard/react-native-swiper-flatlist#34]
Hi, 
I cannot find any notes on how to use getCurrentIndex function, any suggestions perhaps?

Tried: 
```
<SwiperFlatList
            index={this.state.currentSlide}
            showPagination
            ref={(component) => {this._swiper = component}}
          >
            {this.state.slides}
</SwiperFlatList>
```
in order to access getCurrentIndex function in class method like
```
_getIndex = () => {
  let index = this._swiper.getCurrentIndex()
}
```
but after adding ref string my app stops to render at all.

My goal is to monitor current index to conditionally render Next/Previous arrows (like one asked in feature request)

**Comment by greenais** [comment]
UPD:
the issue with ref string was the need to keep ";" in the end of statement (which I removed considering it as unnecessary), like:
`ref={(component) => {this._swiper = component;}}` 
Very surprised.

Anyway, my goal (index tracking) isn't reacheable with just getCurrentIndex as it should be fired automatically after swipe somehow. I ended with following (in case someone will bump here with similar task):
```
<SwiperFlatList
            index={this.state.currentSlide}
            onViewableItemsChanged={this._handleIndexChange}
            viewabilityConfig={{itemVisiblePercentThreshold: 100}}
>
```
and then
```
_handleIndexChange = ({changed}) => {
    let index = changed[0].index;
    this.setState({currentSlide: index}, this._setPrevNextVisibility)
  };
```
Tnx for yor lib, it's really nice

**Comment by gusgard** [comment]
In version 2, you can call getCurrentIndex https://github.com/gusgard/react-native-swiper-flatlist#functions

**Comment by Marcos-Vinicius9** [comment]
I have the same problem

**Comment by Marcos-Vinicius9** [comment]
I have the same problem
