### ISSUE TITLE
Pagination is not correct sometimes on devices

### ISSUE THREAD

**Issue by AsimPoptani** [gusgard/react-native-swiper-flatlist#36]
Pagination is not correct sometimes on devices the content offset /layout measurement gives a number slightly off a whole number, the easy solution to this is to use Math.round instead of Math.floor

**Comment by mtumiati** [comment]
I got the same issue. I tried with your solution and it seems to work fine. I'm going to send a pull request with the fix. Thanks for your proposal.

**Comment by gusgard** [comment]
Thanks for the fix, it will release it today.

**Comment by gusgard** [comment]
Released version 1.0.10. Thank you
