### ISSUE TITLE
Getting memory leak warning

### ISSUE THREAD

**Issue by mahendr** [gusgard/react-native-swiper-flatlist#38]
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.%s,
in SwiperFlatList (at EventScreen.js:94)

This happens when switching screen away from where the swiperFlatList is used. Happens randomly.

I load data={} with a MobX observable array.

What are the tasks to cancel during unmount?

**Comment by gusgard** [comment]
Can you reproduce this issue with version 2? Also, could you add a working example in expo? so I can reproduce it
