### ISSUE TITLE
onchange feature

### ISSUE THREAD

**Issue by GloboM** [gusgard/react-native-swiper-flatlist#41]
Hi there,
is there any way to detect when the index changes

**Comment by sheeshmohsin** [comment]
Any update on this? same question from me as well.

**Comment by IntelliJAbhishek** [comment]
There is a way to detect

    <SwiperFlatList
            index={this.state.currentSlide}
            onViewableItemsChanged={this._handleSlideChange}
    >

**Comment by gusgard** [comment]
Yes, you can use `onChangeIndex`, check the readme https://github.com/gusgard/react-native-swiper-flatlist#functions and a working example in https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/SwiperWithChildren.js#L28
