### ISSUE TITLE
Autoplay is very fast in android 

### ISSUE THREAD

**Issue by IntelliJAbhishek** [gusgard/react-native-swiper-flatlist#42]
Autoplay in android is very fast on Android even if there is 5 second delay added. Here is my code:

    <SwiperFlatList
        autoplay
        autoplayLoop
        autoplayDelay={5}
        showPagination
        paginationActiveColor="black"
        paginationStyleItem={{ width: 10, height: 10, marginHorizontal: 5 }}>
        <View style={styles.child}>
            <Image source={{ uri: 'https://app.tutiixx.com/wp-content/uploads/2018/12/tshirt-banner.jpg' }} style={{ width: null, height: null, flex: 1 }} />
        </View>
        <View style={styles.child}>
            <Image source={{ uri: 'https://s3.envato.com/files/216320406/BEE-1797-Fashion%20Sale%20Banners_01_Preview3.jpg' }} style={{ width: null, height: null, flex: 1 }} />
        </View>
        <View style={styles.child}>
            <Image source={{ uri: 'https://s3.envato.com/files/168119903/BEE-1096-Fashion%20Banners_01_preview4.jpg' }} style={{ width: null, height: null, flex: 1 }} />
        </View>
    </SwiperFlatList>

**Style**

    const { width, height } = Dimensions.get('window');
    const styles = StyleSheet.create({
        child: {
            height: width * 0.60,
            width,
            justifyContent: 'center'
        }
    });

**Comment by gusgard** [comment]
Could you try it in version 2? It should work much better now

**Comment by IntelliJAbhishek** [comment]
@gusgard i will try on manday and inform.

**Comment by IntelliJAbhishek** [comment]
Fixed in 2.0.1

**Comment by IntelliJAbhishek** [comment]
Sorry my mistake its not fixed. It happens on some devices only. It can be reproduce in Galaxy J5

**Comment by gusgard** [comment]
@IntelliJAbhishek Any particular version of Android?

**Comment by IntelliJAbhishek** [comment]
> @IntelliJAbhishek Any particular version of Android? And it only happens with `Image`?

@gusgard  Tried Fast image library too. Same effect it happening in Galaxy J5 running on Lollipop 5.1
Also its happening only during remote debugger is on.

**Comment by gusgard** [comment]
Thanks, @IntelliJAbhishek for the update, I'm glad it is only happening with the debugger and not in production

**Comment by IntelliJAbhishek** [comment]
Yeah @gusgard but its annoying during development hehe
