### ISSUE TITLE
react-native-camera not working in vertical swiper

### ISSUE THREAD

**Issue by sheeshmohsin** [gusgard/react-native-swiper-flatlist#43]
Here is the code:-

```
<SwiperFlatList
  autoplayLoop={false}
  initialScrollIndex={this.state.startIndex}
  showPagination={false}
  vertical={true}
  onViewableItemsChanged={this.handleViewableItemsChanged}
  viewabilityConfig={this.viewabilityConfig}
  initialNumToRender={3}
>
  <View style={[styles.child, { backgroundColor: 'tomato' }]}>
    <Text style={styles.text}>Search</Text>
  </View>
  <View style={{flex: 1}}>
    {this.state.CameraFocus || <CameraComponent></CameraComponent>}
  </View>
  <View style={[styles.child, { backgroundColor: 'skyblue' }]}>
    <Text style={styles.text}>Memories</Text>
  </View>
</SwiperFlatList>
```

On load, the camera is working fine, able to catch stream from the camera, however, once I swipe somewhere either up or down, after that on coming back to the camera screen, the screen goes black i.e. camera not running

This is working fine with horizontal scroll. Let me know If I'm doing something wrong.

**Comment by sheeshmohsin** [comment]
Any help on this?

**Comment by IntelliJAbhishek** [comment]
Just unmount the camera view like this

{this.state.cameraFocused ? <Camera /> : <View />}

**Comment by sheeshmohsin** [comment]
@IntelliJAbhishek  I tried this, but it didn't worked well, as I was using this function for checking if the screen is on camera `onViewableItemsChanged` , but this function fires like 4 times in a row, even if I change from index 1 to index 2.

**Comment by IntelliJAbhishek** [comment]
@sheeshmohsin  use like this

    handleViewableItemsChanged=(e) => {
         this.setState({
             cameraFocused: e.viewableItems[0].index == 1,
        });

Now use like this not efficient but works.
    <View style={styles.child}>
                {this.state.cameraFocused ? <Camera /> : <View />}
    </View>

**Comment by gusgard** [comment]
Could you try version 2 and using `renderItem` instead of `children`?
https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/SwiperWithRenderItems.js#L23
