### ISSUE TITLE
feature request: set swipe treshold

### ISSUE THREAD

**Issue by ammoradi** [gusgard/react-native-swiper-flatlist#44]
there is a needed property like `swipeTreshold=[NUM]` to control the swipe gesture range.
at the moment, I am using horizontal swiper and in `Samsung Galaxy S8` with `Android 9.0` and a few swipes in diameter or with any little angles from the vertical line, it swipes to next item but it should scroll to down.

**Comment by gusgard** [comment]
I will need to dig into the docs but I think FlatList has a property for that behavior. I will let you know

**Comment by gusgard** [comment]
I believe you need to use these properties but are only implemented for iOS
https://facebook.github.io/react-native/docs/scrollview#automaticallyadjustcontentinsets
https://facebook.github.io/react-native/docs/scrollview#directionallockenabled
