### ISSUE TITLE
After upgrading to RN 0.60 get error undefined is not an object(evaluating'_data.length')

### ISSUE THREAD

**Issue by kirhim** [gusgard/react-native-swiper-flatlist#52]
After upgrade to RN 0.60 get this error

`undefined is not an object(evaluating'_data.length')`

How can I fix this?

**Comment by gusgard** [comment]
@kirhim What version are you using of this library? Could you add the code that is failing? It seems you are not sending an array to the SwiperFlatList component. Check these two examples: 
https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/SwiperWithChildren.js and https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/SwiperWithRenderItems.js

**Comment by kirhim** [comment]
@gusgard thanks for the comment. I am using version`"react-native-swiper-flatlist": "^2.0.2"`.
The error code is :  `<SwiperFlatList data={this.state.pictures}/> ` `In this.state.pictures` I am sending image URL.

**Comment by kirhim** [comment]
@gusgard Any idea why this is happening in version 2.0?

**Comment by gusgard** [comment]
Yes, I believe you are not using ` renderItem={({ item }) => <Image style={styles.image} source={item.image} />}` or the `children` prop.
