### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by saggiyogesh** [gusgard/react-native-swiper-flatlist#53]
Hi,
Any plans to add typescript definitions for the library.

**Comment by gusgard** [comment]
Yes, it is in the roadmap for this month.

**Comment by saggiyogesh** [comment]
cool thank 👍

**Comment by bndby** [comment]
What about this?

**Comment by butri71** [comment]
> Yes, it is in the roadmap for this month.

Any new on this yet?

**Comment by 3GOMESz** [comment]
Any news about this?

**Comment by gusgard** [comment]
Sorry, I have been quite busy but I'm planning to do it before the end of the year, with the version number `2.0.7`

**Comment by gusgard** [comment]
Released with version `3.0.0`

https://github.com/gusgard/react-native-swiper-flatlist/pull/90
