### ISSUE TITLE
I ruled out all the problems and suspected that this component has performance issues.

### ISSUE THREAD

**Issue by afeichuanqi** [gusgard/react-native-swiper-flatlist#56]
When I was silent, I found that js and fps dropped once every time.

**Comment by afeichuanqi** [comment]
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.

**Comment by gusgard** [comment]
It seems a problem with the items you are rendering in `renderItem` or `children` prop. Did you try using PureComponent or pure function components?

**Comment by afeichuanqi** [comment]
> It seems a problem with the items you are rendering in `renderItem` or `children` prop. Did you try using PureComponent or pure function components?

My renderitem is not likely to be refreshed again.
I take great care of performance issues so I can rule out my problem with renderitem.

**Comment by afeichuanqi** [comment]
> It seems a problem with the items you are rendering in `renderItem` or `children` prop. Did you try using PureComponent or pure function components?

I have found a suspected bug and it is very serious.
That is, autoplayTimer = setTimeout will be continuously reused.
That is, create setTimeout without limit, you can console.log in the carousel loop.

**Comment by gusgard** [comment]
In that case, could you add an example (maybe in https://snack.expo.io/) so I can take a look? What props are you using?

**Comment by afeichuanqi** [comment]
> In that case, could you add an example (maybe in https://snack.expo.io/) so I can take a look? What props are you using?

React.useEffect(() => {
      const isLastIndexEnd = autoplayInvertDirection
        ? paginationIndex === FIRST_INDEX
        : paginationIndex === _data.length - 1;
      const shouldContinuoWithAutoplay = autoplay && !isLastIndexEnd;
      console.log('React.useEffect');
      let autoplayTimer;
      if (shouldContinuoWithAutoplay || autoplayLoop) {
        console.log('autoplayLoop');
        autoplayTimer = setTimeout(() => {
          const nextIncrement = autoplayInvertDirection ? -1 : +1;

          let nextIndex = (paginationIndex + nextIncrement) % _data.length;
          if (autoplayInvertDirection && nextIndex < FIRST_INDEX) {
            nextIndex = _data.length - 1;
          }

          // When reach the end disable animated
          _scrollToIndex({ index: nextIndex, animated: !isLastIndexEnd });
        }, autoplayDelay * MILLISECONDS);
      }
      // https://upmostly.com/tutorials/settimeout-in-react-components-using-hooks
      return () => clearTimeout(autoplayTimer);
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [paginationIndex]);
you try

**Comment by afeichuanqi** [comment]
> In that case, could you add an example (maybe in https://snack.expo.io/) so I can take a look? What props are you using?

I don't know how you write this. In react-native, I don't know if this is a bug.

**Comment by gusgard** [comment]
Yes, I need some example so I can reproduce it. At least could you tell me the props you are using that are causing that warning? Could also be just a problem in the React Native framework. I'm not sure. Did you try using the `renderAll` prop (it render all the items before display it)?

**Comment by afeichuanqi** [comment]
> Yes, I need some example so I can reproduce it. At least could you tell me the props you are using that are causing that warning? Could also be just a problem in the React Native framework. I'm not sure. Did you try using the `renderAll` prop (it render all the items before display it)?

I have six items when I remove autolook and let him stop looping.
Perform a manual slide.
This warning will appear when sliding to the fourth item, let alone under autolook 
And the rendering situation caused this problem to be unreplicable. It is possible to test the android performance is lower.
But there is no doubt that this component is absolutely problematic.

**Comment by gusgard** [comment]
Please add a working example, so I can take a look, otherwise, it seems a problem with the items inside renderItem/children.

**Comment by afeichuanqi** [comment]
> Please add a working example, so I can take a look, otherwise, it seems a problem with the items inside renderItem/children.

I will give you an example when I have time. I have already found another flatlist to make a carousel.
There is no problem. The performance feel page is normal.
Because you may be the latest version of the react syntax.
