### ISSUE TITLE
Question: how to change the dots size on the pagination bar

### ISSUE THREAD

**Issue by borgogelli** [gusgard/react-native-swiper-flatlist#57]
The pagination dots are too big on some device.
Is there anyone who can provide an example of how to use the paginationStyle and the paginationStyleItem attributes to resize the dots ?
Thank you in advance.

**Comment by SrikaraBhat** [comment]
@borgogelli Got any solution?

**Comment by whitetown** [comment]
paginationStyleItem={{ width:10, height:10, borderRadius:5 }}

**Comment by gusgard** [comment]
You could always re-define a new Pagination component and use it with the prop `PaginationComponent`.

Example https://github.com/gusgard/react-native-swiper-flatlist/blob/master/example/src/SwiperWithChildren.js#L34

**Comment by IbrahimSheikh24** [comment]
Hi gusgard,
showPagination prop not showing any dot on swiper. Please help me on this.

**Comment by gusgard** [comment]
@IbrahimSheikh24 did you use the same code from the example (check https://snack.expo.io/@gusgard/react-native-swiper-flatlist) ? or could you share your code in a snack example?

**Comment by IbrahimSheikh24** [comment]
@gusgard 
<SwiperFlatList
                                autoplay
                                autoplayDelay={5}
                                index={3}
                                autoplayLoop
                                autoplayInvertDirection
                                showPagination>
                                <View style={[styles.child, { backgroundColor: 'thistle' }]}>
                                    <Text style={styles.text}>2</Text></View>
                                    <View style={[styles.child, { backgroundColor: 'skyblue' }]}>
                                    <Text style={styles.text}>3</Text>
                                    </View>
                                    <View style={[styles.child, { backgroundColor: 'teal' }]}>
                                        <Text style={styles.text}>4</Text>
                                    </View>
                            </SwiperFlatList>
This code I ran on snack, dot is showing there, but the same code I am using on my device where dot is not showing.

**Comment by midhungopipk** [comment]
how can we make the position of pagination component fixed at the bottom of screen. in my case pagination component comes along with keyboard when I tap in a text input box. its not staying at the bottom of the screen. i tried position:'absolute'. can any one help? please...


			<SwiperFlatList
				showPagination
				paginationActiveColor="#1061cc"
				paginationStyle={{position:'absolute'}}
				paginationStyleItem={{ width:10, height:10, borderRadius:5,backgroundColor:'red' }}
				index={currentIndex}
				data={KraData}
				renderItem={({ item }) => (
					<View
						style={{
							marginTop: height(10),
							marginHorizontal:
								width(5),
						}}
					>.

                                ........................................./>
