### ISSUE TITLE
[Question/Improvement] How to disable swipe gesture?

### ISSUE THREAD

**Issue by ebellumat** [gusgard/react-native-swiper-flatlist#58]
I will use this component to scroll a view programatically, but i want to prevent the user going to the next step with the swipe gesture, exists any way to disable?

If not, i can open a PR with this improvement?

Thanks.

**Comment by ebellumat** [comment]
I did not find a props for this even reading the code, so i opened a PR with this. I hope it helps.

**Comment by gusgard** [comment]
PR released in version 2.0.3
