### ISSUE TITLE
Unable to modify Pagination size and style

### ISSUE THREAD

**Issue by taichiyi** [gusgard/react-native-swiper-flatlist#6]
The component is very good, thank you open source

**Comment by taichiyi** [comment]
The component is very good, thank you open source

**Comment by gusgard** [comment]
@taichiyi Thanks. I will change it to support a custom pagination component at the weekend

**Comment by gusgard** [comment]
@taichiyi You can use now `PaginationComponent`, check the example https://snack.expo.io/@gusgard/react-native-swiper-flatlist or the code https://github.com/gusgard/react-native-swiper-flatlist/blob/master/src/components/Pagination/index.js

**Comment by taichiyi** [comment]
nice
