### ISSUE TITLE
Swiping only works with teh first index 

### ISSUE THREAD

**Issue by Merrick17** [gusgard/react-native-swiper-flatlist#69]
React Native version:

## Steps To Reproduce

`import React, { useState ,useEffect} from "react";
import { View, StyleSheet, Dimensions, Image } from "react-native";
import { useSelector } from "react-redux";
import { Text } from "galio-framework";
import { GlobalStyles } from "../styles/global";
import Icon from "react-native-vector-icons/FontAwesome";
import { NavBar, Card } from "galio-framework";
import { DrawerActions } from "react-navigation-drawer";
import { format } from "date-fns";
import SwiperFlatList from "react-native-swiper-flatlist";
import NewsDetailsItems from "../components/newsDetailsItem/index";
const NewsDetailsScreen = props => {
  const news = useSelector(state => state.News);

  const newsId = props.navigation.getParam("id");
  const selectedIndex = news.findIndex(elm => elm._id == newsId);

  return (
    <View style={GlobalStyles.psscreen}>
      <NavBar
        title="Latest News"
        transparent={true}
        titleStyle={styles.titleStyle}
        left={
          <Icon
            name="bars"
            style={{
              fontSize: 20,
              color: "white"
            }}
            onPress={() => {
              props.navigation.dispatch(DrawerActions.toggleDrawer());
            }}
          />
        }
        right={
          <Icon
            name="heart"
            style={{
              fontSize: 20,
              color: "white"
            }}
            onPress={() => {
              props.navigation.dispatch(DrawerActions.toggleDrawer());
            }}
          />
        }
      />
      <SwiperFlatList
      
      
        index={selectedIndex}
        data={news}
        renderItem={({ item }) => {
          return (

            <NewsDetailsItems item={item} />
         
          );
        }}
      />
    </View>
  );
};`

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by OsamaHarby** [comment]
i have the same problem

**Comment by gusgard** [comment]
Closed until we have a reproducible example on expo or in a repository.
