### ISSUE TITLE
Support for web

### ISSUE THREAD

**Issue by shakyarahul** [gusgard/react-native-swiper-flatlist#80]
I really appreciate your work. Can you guys make this project support for web too

**Comment by gusgard** [comment]
Thanks, there are a few limitations with react-native-web and FlatList. Check: https://github.com/gusgard/react-native-swiper-flatlist#limitations

**Comment by gusgard** [comment]
We will support react native web these days with version 3.0.9

**Comment by gusgard** [comment]
Added react native web support in 3.0.9
