### ISSUE TITLE
Proposal: Add an extra option to modify style of the active pagination item

### ISSUE THREAD

**Issue by MihailoCherryz** [gusgard/react-native-swiper-flatlist#88]
## What problem are we trying to solve?
Upon integrating `react-native-swiper-flatlist` into an existing React Native project we needed a way to differentiate between an active option (dot) and inactive ones and apply different styling to each of them.
## Why should we solve it?
While we appreciate that other apps might not need or even require this particular option, its addition would allow for more control over the styling of pagination options, both active and inactive.
## How do we propose to solve it?
We already have a patch file that adds this option to the js layer.
A further change would be to update documentation to detail this change.
## What could go wrong?
This option would default to the main `paginationStyleItem` which would closely match current expected behaviour.

**Comment by gusgard** [comment]
Added the properties `paginationStyleItemActive` and `paginationStyleItemInactive` in version `2.0.7`
