### ISSUE TITLE
Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.

### ISSUE THREAD

**Issue by justinhorner** [gusgard/react-native-swiper-flatlist#9]
It looks like in a recent ReactNative update, the virtualizedCell.cellKey should be string instead of number.  

https://github.com/wonday/react-native-pdf/issues/125
https://github.com/status-im/status-react/pull/3387

More of the error:

Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.
    in CellRenderer (at VirtualizedList.js:668)
    in RCTScrollContentView (at ScrollView.js:793)
    in RCTScrollView (at ScrollView.js:889)
    in ScrollView (at VirtualizedList.js:998)
    in VirtualizedList (at FlatList.js:640)
    in FlatList (at index.js:200)
    ...

**Comment by justinhorner** [comment]
PR with proposed fix: https://github.com/gusgard/react-native-swiper-flatlist/pull/10

**Comment by gusgard** [comment]
Thanks for the issue and the PR, it will be merged in a few minutes
