### ISSUE TITLE
Contrary to documentation, onPaginationSelectedIndex() does not have any parameters

### ISSUE THREAD

**Issue by jasperSpeicher** [gusgard/react-native-swiper-flatlist#92]
https://github.com/gusgard/react-native-swiper-flatlist/blob/c83ee31c568ec204be5ff8cfe33082984fe3773b/src/components/Pagination/Pagination.tsx#L33

**Comment by gusgard** [comment]
> [react-native-swiper-flatlist/src/components/Pagination/Pagination.tsx](https://github.com/gusgard/react-native-swiper-flatlist/blob/c83ee31c568ec204be5ff8cfe33082984fe3773b/src/components/Pagination/Pagination.tsx#L33)
> Line 33 in [c83ee31](/gusgard/react-native-swiper-flatlist/commit/c83ee31c568ec204be5ff8cfe33082984fe3773b)
>  onPaginationSelectedIndex?: () => void;

Hey 👋, I check and the method `onPaginationSelectedIndex` seem to have the correct values, if not could you add the wrong example of the documentation ?

Thanks.

**Comment by jasperSpeicher** [comment]
The readme says: "similar properties onChangeIndex"
https://github.com/gusgard/react-native-swiper-flatlist/blame/master/README.md#L116

Any reason not to include the index?
