### ISSUE TITLE
Cannot disable pagination taps

### ISSUE THREAD

**Issue by jasperSpeicher** [gusgard/react-native-swiper-flatlist#93]
Unlike swiping interactions, pagination taps cannot be prevented from changing the index.

**Comment by gusgard** [comment]
Hey 👋, I think you are looking for the property `showPagination` to disable the pagination.

**Comment by jasperSpeicher** [comment]
@gusgard I want to see the pagination dots, but I do not want the user to be able to tap them to change the index.
