### ISSUE TITLE
I can not run example code folder.

### ISSUE THREAD

**Issue by Ppang0405** [gusgard/react-native-swiper-flatlist#94]
**Log**
`➜  example git:(master) yarn                                                                           
yarn install v1.22.10                                                                                  
[1/4] 🔍  Resolving packages...                                                                        
[2/4] 🚚  Fetching packages...                                                                         
[3/4] 🔗  Linking dependencies...                                                                      
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
[4/4] 🔨  Building fresh packages...                                                                   
[-/5] ⠈ waiting...                                                                                     
[-/5] ⠈ waiting...                                                                                     
[-/5] ⠈ waiting...                                                                                     
[5/5] ⠈ detox                                                                                          
error /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox
Output:
+ xcodebuild -version
+++ dirname /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/scripts
+ detoxRootPath=/Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox
++ node -p 'require('\''/Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/package.json'\'').version'
+ detoxVersion=14.0.1
++ echo 14.0.1
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=098ecae8afed136365baf4240ed3994873fecc52
+ detoxFrameworkDirPath=/Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52
+ detoxFrameworkPath=/Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52/Detox.framework
+ main
+ '[' -d /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52 ']'
+ '[' '!' -d /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52/Detox.framework ']'
+ echo '/Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52 and trying to rebuild.'
+ rm -rf /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52
/Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52 and trying to rebuild.
+ prepareAndBuildFramework
+ '[' -d /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ extractSources /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ detoxSourcePath=/Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ tar -xjf /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/Detox-ios-src.tbz -C /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ buildFramework /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ detoxSourcePath=/Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src...'
+ mkdir -p /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52
Building Detox.framework from /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src...
+ /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/scripts/build_universal_framework.sh /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/ios_src/Detox.xcodeproj /Users/truongnguyen/Library/Detox/ios/098ecae8afed136365baf4240ed3994873fecc52
child_process.js:637
    throw err;
    ^

Error: Command failed: /Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.<anonymous> (/Users/truongnguyen/Desktop/react-native-swiper-flatlist/example/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 18905,`

React Native version:

## Steps To Reproduce

1. clone this project
2. cd example, yarn, -> yarn fail

Describe what you expected to happen:
I do not know what happens. Why yarn fail??

**Comment by gusgard** [comment]
Which version of nodejs and Xcode are you using ?

 I’m guessing the issue is with the detox dependency. Could you check these links ? Or remove `detox` from the `package.json`?

https://github.com/wix/Detox#environment
https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md#step-1-environment-setup

**Comment by Ppang0405** [comment]
Close this issue. I remove detox as you suggest and it works.
