### ISSUE TITLE
Show some part of next and previous slide

### ISSUE THREAD

**Issue by abuzer** [gusgard/react-native-swiper-flatlist#96]
How can we show the some part of next slide and previous slide? Can this be achieved with this package?

**Comment by gusgard** [comment]
Yes, it can be done. Example https://snack.expo.io/@gusgard/react-native-swiper-flatlist-show-next-screen

**Comment by abuzer** [comment]
Thanks. I would need another favour. If you can guide me how can we something like this.
![Uploading Screenshot 2020-12-29 at 8.44.39 PM.png…]()

**Comment by gusgard** [comment]
That type of questions should be in `Discussions` section so someone can help you with the stylesheets
