### ISSUE TITLE
horizontal ScrollView inside swiper is not working

### ISSUE THREAD

**Issue by RicardoBrito1938** [gusgard/react-native-swiper-flatlist#99]
Hello, congratulations for the tool it is really helpfull, but i am facing an issue with horizontal a Horizontal ScrollView inside flatlist

![image](https://user-images.githubusercontent.com/51454097/104017597-281f8d00-5197-11eb-95f7-b118be0da080.png)

React Native version:
0.63

## Steps To Reproduce
```

   <SwiperFlatList onChangeIndex={handleChangeTab} ref={scrollRefSwipe}>
          <View style={{ width }}>
            {!failedGetFeeds ? renderHome : renderEmptyState}
          </View>
          <View style={{ width }}>{renderActivities}</View>
          <View style={{ width }}>{renderDashboard}</View>
        </SwiperFlatList>
```
the last render (renderDashboar), is a horizontal scrollview, it is stoped working after i implemented the swiper flatlist

Describe what you expected to happen:
I nedd to make my horizontal list work again, not sure if it is needed some configuration

**Comment by gusgard** [comment]
Hey 👋 , I think you should try the property `renderAll` to render everything.

BTW: this is a working example https://snack.expo.io/@gusgard/react-native-swiper-flatlist-using-scrollview using horizontal ScrollView.

**Comment by RicardoBrito1938** [comment]
> Hey  , I think you should try the property `renderAll` to render everything.
> 
> BTW: this is a working example https://snack.expo.io/@gusgard/react-native-swiper-flatlist-using-scrollview using horizontal ScrollView.

Hello Gustavo, thank you very much for the reply, i believe i am closer, but it is not working yet, your example, the swiper is horizontal, which is correct, but scroll of the second view is still vertical, i tried to apply the horizontal on the second view, but it does not have priority over the swiper, please take a look on changes i did on your example

![image](https://user-images.githubusercontent.com/51454097/104093018-81a2bd00-5266-11eb-875a-7390c6e3508f.png)


of

**Comment by gusgard** [comment]
Check this other example: https://snack.expo.io/@gusgard/react-native-swiper-flatlist-using-scrollview-example

```jsx
const App = () => (
  <View style={styles.container}>
    <SwiperFlatList renderAll>
      <View style={[styles.child, { backgroundColor: 'thistle' }]}>
        <Text style={styles.text}>1</Text>
      </View>
      <View>
        <ScrollView horizontal>
          <View style={[styles.child,{ backgroundColor: 'tomato'}]}>
            <Text style={styles.text}>5.1</Text>
          </View>
          <View style={[styles.child,{ backgroundColor: 'skyblue' }]}>
            <Text style={styles.text}>5.2</Text>
          </View>
          <View style={[styles.child,{ backgroundColor: 'teal' }]}>
            <Text style={styles.text}>5.3</Text>
          </View>
        </ScrollView>
      </View>
      <View style={[styles.child, { backgroundColor: 'thistle' }]}>
        <Text style={styles.text}>10</Text>
      </View>
    </SwiperFlatList>
  </View>
);
```

BTW: I recommend you to not have horizontal list inside another horizontal list, at least for me it makes sense to have vertical list inside horizontals or the opposite

**Comment by RicardoBrito1938** [comment]
@gusgard  you are the best, it really works, but Scroll items must have the same height, for a different, it adjusts to work on same height, in any case, you helped me a lot, i will follow you advice and reach out to team requesting a change, even for a experience user, that may be confusing, i will close the issue, thank you very much one more time
